services:
  # Backend API service
  - type: web
    name: gmc-ecco-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FRONTEND_URL
        value: https://gmc-ecco-frontend.onrender.com
      - key: PORT
        value: 10000
    
  # Frontend React application
  - type: static
    name: gmc-ecco-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: REACT_APP_BACKEND_URL
        value: https://gmc-ecco-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 